### ISSUE TITLE
check-wininstaller-translations.sh script doesn't detect regional translation files

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1966]
If you want to work on this, you should know bash (and maybe do a bit internet research).
**Describe the bug**
While reviewing https://github.com/jamulussoftware/jamulus/pull/1954#pullrequestreview-735564504 I found out that check-wininstaller-translations.sh does NOT check files which do not follow `??.nsi`. We're only checking for languages with two letters here: https://github.com/jamulussoftware/jamulus/blob/417a9bc8c26cdf06fb301cdfaa96e3f875a52666/tools/check-wininstaller-translations.sh#L7

**To Reproduce**
Run the script and review the output. E.g pt_br doesn't get checked.

**Expected behavior**
All files get checked by the script.

**Screenshots**
n/a

**Operating system**
Debian Linux
**Version of Jamulus**
n/a

**Todo**
- [ ] Research how to match file names like es.nsi, de.nsi and also en_US.nsi especially have a look at: https://www.linuxjournal.com/content/pattern-matching-bash
- [ ] Comment on this issue how you plan to solve the problem
- [ ] Test your changes locally
- [ ] Raise a pull request
- [ ] Ping @ann0see or any other Jamulus main developer.

**Comment by ignotus666** [comment]
Just added ??_??.nsi, which enables checking for xx_XX or xx_xx formats. Pinging @ann0see. PR: #2007

**Comment by ignotus666** [comment]
BTW, the script reports an error with zh_cn.nsi:

```
- Checking for LangStrings diffs... WARNING, differences found:
--- /dev/fd/63	2021-09-09 12:02:43.988161262 +0200
+++ /dev/fd/62	2021-09-09 12:02:43.989161256 +0200
```

**Comment by ann0see** [comment]
> Just added ??_??.nsi, which enables checking for xx_XX or xx_xx formats

But this wouldn’t allow the xx.nsi format.

Concerning the Chinese translation, maybe ask Blumina in the PR?

**Comment by ignotus666** [comment]
> But this wouldn’t allow the xx.nsi format.

I added `{??.nsi,??_??.nsi}` so both are covered.

Yes, I'll ping him there. The Chinese .nsi file seems to be missing a few LangStrings.
